LavaFlow:
  Components:
    - LavaFlow-Tech/Andesite
    - LavaFlow-Tech/Ash
    - LavaFlow-Tech/Cinder
    - LavaFlow-Tech/Igneous
    - LavaFlow-Tech/Mica
    - LavaFlow-Tech/Pyro
    - LavaFlow-Tech/Silica
  Objects:
    - Project
    - Scene
    - Canvas